# Generated by Django 3.1.3 on 2021-11-07 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yetiMP3', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UniqueTaskId',
        ),
        migrations.RemoveField(
            model_name='task',
            name='task_id',
        ),
    ]
